# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14IW8RhyK3o_2ymWndL6UPfSCtuxJnw-p
"""

# -*- coding: utf-8 -*-
import csv
import matplotlib.pyplot as plt

# ══════════════════════════════════════════════════════════════════════════════
#  Загрузка CSV
# ══════════════════════════════════════════════════════════════════════════════
def load_statistics(filename):
    data = {}  # data[generator] = {'mean': [], 'stddev': [], 'cv': [], 'p_value': [], 'uniform': []}
    with open(filename, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            g = row['generator']
            if g not in data:
                data[g] = {'sample': [], 'mean': [], 'stddev': [], 'cv': [], 'p_value': [], 'uniform': []}
            data[g]['sample'].append(int(row['sample']))
            data[g]['mean'].append(float(row['mean']))
            data[g]['stddev'].append(float(row['stddev']))
            data[g]['cv'].append(float(row['cv']))
            data[g]['p_value'].append(float(row['p_value']))
            data[g]['uniform'].append(int(row['uniform']))
    return data

def load_nist(filename):
    data = {}  # data[generator] = {'test_name': [], 'p_value': [], 'passed': []}
    with open(filename, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            g = row['generator']
            if g not in data:
                data[g] = {'test_name': [], 'p_value': [], 'passed': []}
            data[g]['test_name'].append(row['test_name'])
            data[g]['p_value'].append(float(row['p_value']))
            data[g]['passed'].append(int(row['passed']))
    return data

def load_timing(filename):
    sizes = []
    cs    = []
    acc   = []
    qx    = []
    std   = []
    with open(filename, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            sizes.append(int(row['size']))
            cs.append(float(row['CrossState']))
            acc.append(float(row['XorShiftACC']))
            qx.append(float(row['QuadXOR']))
            std.append(float(row['StdRand']))
    return sizes, cs, acc, qx, std

# ══════════════════════════════════════════════════════════════════════════════
#  График 1: Среднее по выборкам для каждого генератора
# ══════════════════════════════════════════════════════════════════════════════
def plot_mean(data):
    fig, ax = plt.subplots(figsize=(10, 6))
    for g, d in data.items():
        ax.plot(d['sample'], d['mean'], marker='o', label=g)
    ax.set_title('Среднее значение по выборкам')
    ax.set_xlabel('Номер выборки')
    ax.set_ylabel('Среднее')
    ax.legend()
    ax.grid(True)
    plt.tight_layout()
    plt.savefig('plot_mean.png', dpi=150)
    plt.close()
    print('Сохранено: plot_mean.png')

# ══════════════════════════════════════════════════════════════════════════════
#  График 2: Стандартное отклонение по выборкам
# ══════════════════════════════════════════════════════════════════════════════
def plot_stddev(data):
    fig, ax = plt.subplots(figsize=(10, 6))
    for g, d in data.items():
        ax.plot(d['sample'], d['stddev'], marker='o', label=g)
    ax.set_title('Стандартное отклонение по выборкам')
    ax.set_xlabel('Номер выборки')
    ax.set_ylabel('Стандартное отклонение')
    ax.legend()
    ax.grid(True)
    plt.tight_layout()
    plt.savefig('plot_stddev.png', dpi=150)
    plt.close()
    print('Сохранено: plot_stddev.png')

# ══════════════════════════════════════════════════════════════════════════════
#  График 3: Коэффициент вариации по выборкам
# ══════════════════════════════════════════════════════════════════════════════
def plot_cv(data):
    fig, ax = plt.subplots(figsize=(10, 6))
    for g, d in data.items():
        ax.plot(d['sample'], d['cv'], marker='o', label=g)
    ax.set_title('Коэффициент вариации по выборкам')
    ax.set_xlabel('Номер выборки')
    ax.set_ylabel('CV (%)')
    ax.legend()
    ax.grid(True)
    plt.tight_layout()
    plt.savefig('plot_cv.png', dpi=150)
    plt.close()
    print('Сохранено: plot_cv.png')

# ══════════════════════════════════════════════════════════════════════════════
#  График 4: p-value хи-квадрат по выборкам + граница 0.05
# ══════════════════════════════════════════════════════════════════════════════
def plot_chi_pvalue(data):
    fig, ax = plt.subplots(figsize=(10, 6))
    for g, d in data.items():
        ax.plot(d['sample'], d['p_value'], marker='o', label=g)
    ax.axhline(y=0.05, color='red', linestyle='--', label='p = 0.05')
    ax.set_title('p-value критерия хи-квадрат по выборкам')
    ax.set_xlabel('Номер выборки')
    ax.set_ylabel('p-value')
    ax.legend()
    ax.grid(True)
    plt.tight_layout()
    plt.savefig('plot_chi_pvalue.png', dpi=150)
    plt.close()
    print('Сохранено: plot_chi_pvalue.png')

# ══════════════════════════════════════════════════════════════════════════════
#  График 5: p-value NIST тестов (столбчатый, по генераторам)
# ══════════════════════════════════════════════════════════════════════════════
def plot_nist(data):
    generators = list(data.keys())
    tests      = data[generators[0]]['test_name']
    n_tests    = len(tests)
    n_gen      = len(generators)

    x     = list(range(n_tests))
    width = 0.25

    fig, ax = plt.subplots(figsize=(12, 6))
    for i, g in enumerate(generators):
        offsets = [xi + i * width for xi in x]
        pvals   = data[g]['p_value']
        ax.bar(offsets, pvals, width=width, label=g)

    ax.axhline(y=0.01, color='red', linestyle='--', label='p = 0.01 (NIST)')
    ax.set_title('p-value NIST тестов по генераторам')
    ax.set_xlabel('Тест')
    ax.set_ylabel('p-value')
    ax.set_xticks([xi + width * (n_gen - 1) / 2 for xi in x])
    ax.set_xticklabels(tests, rotation=15, ha='right')
    ax.legend()
    ax.grid(True, axis='y')
    plt.tight_layout()
    plt.savefig('plot_nist.png', dpi=150)
    plt.close()
    print('Сохранено: plot_nist.png')

# ══════════════════════════════════════════════════════════════════════════════
#  График 6: Время генерации — все генераторы
# ══════════════════════════════════════════════════════════════════════════════
def plot_timing_all(sizes, cs, acc, qx, std):
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.plot(sizes, cs,  marker='o', label='CrossState')
    ax.plot(sizes, acc, marker='o', label='XorShiftACC')
    ax.plot(sizes, qx,  marker='o', label='QuadXOR')
    ax.plot(sizes, std, marker='o', label='std::rand')
    ax.set_title('Время генерации (все генераторы)')
    ax.set_xlabel('Количество чисел (N)')
    ax.set_ylabel('Время (мс)')
    ax.legend()
    ax.grid(True)
    plt.tight_layout()
    plt.savefig('plot_timing_all.png', dpi=150)
    plt.close()
    print('Сохранено: plot_timing_all.png')

# ══════════════════════════════════════════════════════════════════════════════
#  График 7: Время генерации — только наши генераторы (без std::rand)
# ══════════════════════════════════════════════════════════════════════════════
def plot_timing_ours(sizes, cs, acc, qx):
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.plot(sizes, cs,  marker='o', label='CrossState')
    ax.plot(sizes, acc, marker='o', label='XorShiftACC')
    ax.plot(sizes, qx,  marker='o', label='QuadXOR')
    ax.set_title('Время генерации (наши генераторы)')
    ax.set_xlabel('Количество чисел (N)')
    ax.set_ylabel('Время (мс)')
    ax.legend()
    ax.grid(True)
    plt.tight_layout()
    plt.savefig('plot_timing_ours.png', dpi=150)
    plt.close()
    print('Сохранено: plot_timing_ours.png')

# ══════════════════════════════════════════════════════════════════════════════
#  main
# ══════════════════════════════════════════════════════════════════════════════
def main():
    stats = load_statistics('statistics.csv')
    nist  = load_nist('nist_tests.csv')
    sizes, cs, acc, qx, std = load_timing('timing.csv')

    plot_mean(stats)
    plot_stddev(stats)
    plot_cv(stats)
    plot_chi_pvalue(stats)
    plot_nist(nist)
    plot_timing_all(sizes, cs, acc, qx, std)
    plot_timing_ours(sizes, cs, acc, qx)

if __name__ == '__main__':
    main()